name: 'lint'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.68.0
          environments: lint

      - name: Run linting and formatting checks
        run: pixi run lint
